version: 1.0.{build}

install:
    - pip install -r requirements.txt

build_script:
    - flet pack FetchFlow/main.py --name FetchFlow --icon assets/favicon.png --product-name FetchFlow --product-version "{version}" --copyright "Copyright (c) 2024 CrazyFlyKite"

for:
    -   matrix:
            only:
                -   image: Visual Studio 2019

        artifacts:
            -   path: fetchflow-windows.zip
    -   matrix:
            only:
                -   image: macOS

        artifacts:
            -   path: fetchflow-macos.tar.gz
    -   matrix:
            only:
                -   image: Ubuntu

        artifacts:
            -   path: fetchflow-linux.tar.gz