version: 1.0.{build}

install:
    - pip install -r requirements.txt

build_script:
    - flet pack FetchFlow/main.py --name FetchFlow --icon assets/favicon.png --product-name FetchFlow --product-version "{version}" --copyright "Copyright (c) 2024 CrazyFlyKite"